import * as Discord from "discord.js";
import { IBotEvent } from "../api/eapi";
import Titles from "../util/Titles";
import { ButtonStyle, Collection } from "discord.js";
import { QuickDB } from "quick.db";
const db = new QuickDB();
var standings = db.table('rank');
var history = db.table('history');
var MLonMG = db.table('MLonMG');
var channelLogs = db.table('channelLogs');
var channelPromptLog = db.table('channelPromptLog');
// @ts-ignore
import * as glicko2 from "glicko2";
import { generateResponse } from "../util/UserEmulator/eval.js";

//var Filter = require('bad-words'); //npm install badwords
//let filter = new Filter();
var count = 0;

export default class amogML implements IBotEvent {

    name(): string {
        return "AMOG ML";
    }

    help(): string {
        return "AMOG ML";
    }       
    
    cleanup(content: string[], channelName: string, Bot: Discord.Client): string {
        return `<BOS><CHANNEL_${channelName}> ` + content.map(msg => {
            // Replace emotes: capture the name between <: and : followed by digits and >
            let cleaned = msg.replace(/<:([^:]+):\d+>/g, ':$1:');
    
            // Replace user mentions: capture the ID in <@!ID> or <@ID>
            cleaned = cleaned.replace(/<@!?(\d+)>/g, (match, userId) => {
                const user = Bot.users.cache.get(userId);
                return user ? `@${user.username}` : match;
            });
    
            return cleaned;
        }).join("\n") + "\n";
    }

    private sanitizeContent(msg: string, Bot: Discord.Client): string {
        let cleaned = msg.replace(/<:([^:]+):\d+>/g, ':$1:');
        cleaned = cleaned.replace(/<@!?(\d+)>/g, (match, userId) => {
            const user = Bot.users.cache.get(userId);
            return user ? `@${user.username}` : match;
        });
        return cleaned;
    }

    private async buildPromptForChannel(channel: Discord.TextChannel, Bot: Discord.Client): Promise<string> {
        type LoggedMessage = { userId: string; content: string };
        const allLogs: LoggedMessage[] = (await channelLogs.get(channel.id)) || [];
        const maxMessages = 5; // use only the last 5 messages
        const recent = allLogs.slice(-maxMessages);
        const header = `<CHAN:${channel.name}>`;
        const body = recent.map(m => `
<USR:${m.userId}> ${this.sanitizeContent(m.content, Bot)} <EOM>`).join("");
        const completion = `\n<USR:260118674306760705>\n\n### Completion:\n<USR:260118674306760705>`;
        return header + body + completion;
    }
    
    /**
     * Replaces emoji tokens (e.g. :kekw:) in the text with the corresponding emoji from the guild.
     * If an emoji is not found, it leaves the text as is.
     * @param content - The string content generated by the model.
     * @param Bot - The Discord client instance to access the emoji cache.
     * @returns The processed string with tokens replaced.
     */
    cleandown(content: string, Bot: Discord.Client): string {
        // Replace emoji tokens in the form :emojiName:
        return content.replace(/:([a-zA-Z0-9_]+):/g, (match, emojiName) => {
            const emoji = Bot.emojis.cache.find(e => e.name === emojiName);
            return emoji ? emoji.toString() : match;
        });
    }
    
    
    async runEvent(msg: Discord.Message, Bot: Discord.Client): Promise<void> {
       if (!msg.channel.isTextBased()) return;

       return; // Temporarily disable the bot's response functionality

       let channel = msg.channel as Discord.TextChannel;
      // if (msg.guild!.id != '838203182630305822') return;
      //console.log(msg.content);

        // Append every message to per-channel logs
        try {
            const existing: { userId: string; content: string }[] = (await channelLogs.get(channel.id)) || [];
            existing.push({ userId: msg.author.id, content: msg.content });
            await channelLogs.set(channel.id, existing);
        } catch (e) {
            console.error('Failed to append to channelLogs:', e);
        }

        // Do not respond to bot messages (including self), but they are logged above
        if (msg.author.bot) return;

        let msgList: { content: string, channel: string }[] = (await MLonMG.get(msg.author.id)) || [];
        
            
        msgList.push({content: msg.content, channel: msg.channel.id});

       // const emoji = msg.guild!.emojis.cache.find(e => e.name === "ithink");
        
        if (msgList.length >= 8) {
            msgList.shift();
        }
       // msg.reply("You have sent " + JSON.stringify(msgList));

        
        await MLonMG.set(msg.author.id, msgList);
        let v = (msg.content.toLowerCase().includes("linty") && msg.author.id != '237844886030778368')  ? "" : "polaris, ";
        if (msg.author.id == '260118674306760705'){
            v = 'moni, '
        }
        if (msg.author.id == '115926183576731656')
            v = 'Wa Floyd, '

        if (msg.author.id == '118663865264242688')
            v = "snow hu, "

        let shouldRespond =
            msgList.length > 0 &&
            (
                msg.content.toLowerCase().includes("linty") ||
                msg.author.id == '260118674306760705' ||
                msg.author.id == '237844886030778368' ||
                msg.author.id == '115926183576731656' ||
                msg.author.id == '118663865264242688'
            );

        if (shouldRespond) { 
          //  const allSameChannel = msgList.every(m => m.channel === msg.channel.id);
           // console.log("All messages in the same channel");
            if (msg.content.toLowerCase().includes("linty") || Math.random() < 0.01) { 
                const msgChannel: Discord.Channel = Bot.channels.cache.get(msgList[0].channel) as Discord.Channel;
                if (msgChannel instanceof Discord.TextChannel){
                    console.log("Generating response...");
                    console.log("BOt has token [amogML]: " + Bot.token);
                    await channel.sendTyping(); // Simulate typing 
                    const prompt = await this.buildPromptForChannel(channel, Bot);
                    console.log(prompt);
                    try {
                        const existingPrompts: string[] = (await channelPromptLog.get(channel.id)) || [];
                        existingPrompts.push(prompt);
                        await channelPromptLog.set(channel.id, existingPrompts);
                    } catch (e) {
                        console.error('Failed to log prompt:', e);
                    }
                    generateResponse(prompt).then((response) => {
                    msg.reply(`${v}${this.cleandown(response,Bot)}`);
            });
        }

                
        }

        }
    
    }
    
}


/**
 * You have sent [{"content":":kekw","channel":"1065644982213542020"},{"content":"<:ithink:1343813757331181689>","channel":"1065644982213542020"}]<:ithink:1343813757331181689>
 */
